import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.css";
import { Providers } from "./components/provider";
import { ThemeProvider } from "@/components/theme-provider";
import { SpeedInsights } from "@vercel/speed-insights/next";
// import { SessionProvider } from "next-auth/react";
// import SessionProviderWrapper from "@/components/SessionProviderWrapper";
// import { useSession } from "next-auth/react";

import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";

import { Toaster } from "react-hot-toast";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "TuneVibe",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Theme>
                        <Providers>{children}</Providers>
                    </Theme>
                </ThemeProvider>
                <SpeedInsights />
                <Toaster />
            </body>
        </html>
    );
}
